### ISSUE TITLE
Why so few python libraries?

### ISSUE THREAD

**Issue by cryptid11** [igorbarinov/awesome-bitcoin#11]
Why not adding also the most famous 2:
https://github.com/vbuterin/pybitcointools
https://github.com/petertodd/python-bitcoinlib
?

**Comment by igorbarinov** [comment]
Please add them with small description in PR. I appreciate your help

**Comment by cryptid11** [comment]
ok. but PR is puerto rico or public relations? :)

**Comment by igorbarinov** [comment]
Pull request

**Comment by cryptid11** [comment]
It's interesting you told me this after I already do it.... XD
