### ISSUE TITLE
Adding "Bitcoin Programming with BitcoinJS and Bitcoin Core CLI" guide 

### ISSUE THREAD

**Issue by Janaka-Steph** [igorbarinov/awesome-bitcoin#39]
Hello,

Thank you for this awesome list. 
May I suggest a BitcoinJS guide I wrote?
[Bitcoin Programming with BitcoinJS and Bitcoin Core CLI](https://github.com/bitcoin-studio/Bitcoin-Programming-with-BitcoinJS) 

Thank you

**Comment by Overtorment** [comment]
Hi! Guide looks great, will read it later.
Send a PR to "Read" section.

**Comment by Overtorment** [comment]
@Janaka-Steph are you going to send a PR?

**Comment by Janaka-Steph** [comment]
I don't understand, I sent it 9 days ago. https://github.com/igorbarinov/awesome-bitcoin/pull/41
